### ISSUE TITLE
Set the parent of uploaded media to the current post

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#299]
From a user:

> When I upload an image to a post, the parent for the image is not set to the current post.
>
It would be nice if it was. My use case was to upload a bunch of posts and then replace the image markup with the gallery Shortcode.
>
It would require saving the post first so we can get an id, but I don’t think that’s unusual as it’s something that core does too with auto-drafts.

**Comment by SergioEstevao** [comment]
Using the REST API this will only be possible when we update to version [1.1](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/%24media_ID/)of the API. 

Version [1.0]  (https://developer.wordpress.com/docs/api/1/post/sites/%24site/media/%24media_ID/)] cannot change this parameter.

So this issue is dependent oo this one: https://github.com/wordpress-mobile/WordPress-iOS/issues/2989

**Comment by SergioEstevao** [comment]
Closing this issue because it's a duplicated of this one: https://github.com/wordpress-mobile/WordPress-iOS/issues/4942 and it's being solved here: https://github.com/wordpress-mobile/WordPress-iOS/pull/5095
