### ISSUE TITLE
Cursor position off when uploading media

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#467]
While media is uploading, cursor is set mid-character if you type anything
video: https://lookback.io/watch/LimcMv7sawEmEfrRX

![](https://cloudup.com/i3pdieqM7Vs+)

repro: 
- create post
- add media
- while media is loading, type words

**Comment by meremagee** [comment]
moving to 4.9 - media milestone (a fix here forces a regression on #422 & #421)

**Comment by SergioEstevao** [comment]
I've been working on this and found why this happens and some possible workarounds.

The reason we see the caret in the wrong position is a combination of using:
 * content-editable=false on the elements surrounding the image while it's uploading.
 * and using a hidden-char around the images to allow to be able to select around the images.

The content-editable=false cannot be removed or else the users will be able to remove the uploading style and progress bar while it's happening.

If we remove the hidden-char we have two main limitation:
 * we cannot position the caret near the image if there is no characters around it. This is noticeable if you have a complete empty post and add one or more images or if you insert multiple images and then  want to add text in between images.
 * We cannot "Select All" the content of the post. This issue only happens while the uploading is happening. After the upload is finished the problem is solved because we remove the extra elements and the content-editable=false.

The best solution/workaround I found out is to replace the hidden-char by a &nbsp;. This allows all functionality to still work  with the only downside of adding extra tags on the html and some space between images.

What do you guys think? @meremagee @bummytime @diegoreymendez @thianhlu

**Comment by meremagee** [comment]
wondering what the implications would be in adding  `&nbsp;`s would be against https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/500

**Comment by diegoreymendez** [comment]
I think having a slightly misaligned but fixable caret position is less risky at this point for 4.8, than going for a change.  Just my 2 cents though.
