### ISSUE TITLE
Missing paragraph tag when starting with img, ol, or ul

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#506]
When creating a new post (or deleting all the text out of an exiting one), if the user inserts an image, ```ul```, or ```ol``` the subsequent text is not wrapped in a ```p```.  Video of it here:

https://cloudup.com/cPXLkdquJrL

Ref #367

**Comment by rachelmcr** [comment]
The editor no longer wraps text in `p` tags at all. Instead, paragraphs are separated with two lines breaks in the HTML view. Screenshots: https://cloudup.com/caKwmWIW01L

That behavior is consistent with the Calypso and WP Admin editors. Screenshots: https://cloudup.com/cDXNCncP-ou

The end result is that the initial `img`, `ol`, or `ul` is not wrapped in `p` tags, and the rest of the text in the post is. However, since that is consistent across platforms, I think we can consider it expected behavior here.

Tested in WPiOS 6.2.0.20160429 using iPhone 6, iOS 9.3.1 and in EditorDemo using a simulator.
