### ISSUE TITLE
Discard button deletes the entire post with local drafts

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Editor-iOS#59]
Original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/202

When editing a post, hit cancel to bring up the options "Discard" and "Save Draft". Hitting "Discard" doesn't actually discard the changes the user has made, it deletes the entire post. This only happens on local drafts, not on posts that are already live.

I wonder if we should change the wording to either reflect this, or change the functionality to only discard the changes as the label suggests.

**Comment by meremagee** [comment]
It discards changes made since the last time the post was saved, so if the post is one that had previously saved content, it will not discard all the content - it will remove the recent local edits and maintain the saved/published contents from before as expected.

If the post is a locally saved draft that was created all in one session (never been saved/published), we throw this alert upon opening the post:

![](https://cloudup.com/ipnLAUTN_-z+)

How likely is it that the user ignores the alert, adds to the post, hits cancel, opts to discard, and expects the previous local draft to remain?

**Comment by diegoreymendez** [comment]
@astralbodies - I agree with @meremagee on this one.  I know this can feel a bit dangerous for users, but there's a specific dialog when the post is opened to explain to the user they need to save the post.

To be honest I think that a good alternative to this could be to force-saving posts as draft at certain checkpoints.  Thoughts on this? (also ping @meremagee, @rachelmcr).

**Comment by diegoreymendez** [comment]
PS: there's also a technical reason why I recommend against trying to offer this functionality - we'd need to offer more than 1 level of post revision objects in CoreData, which could bring a lot of different issues.

**Comment by astralbodies** [comment]
This issue was originally from 2013 and was moved into this repo. I'm okay with closing it for now.

**Comment by diegoreymendez** [comment]
Closing.
