### ISSUE TITLE
First character in title & body duplicated in some languages

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#590]
For example: japanese - if you type “tesuto” (= “test”), it should be converted to “てすと” with some alternative options above the keyboard. However, it becomes “ててすと” with an extra letter “て” in front.

![](https://cloudup.com/cQoFPuM0eBR+)

**Comment by coreh** [comment]
Is that input inside of the WebView? If so, this could be caused by repositioning the cursor/changing content during an IME composition. We've hit this on Automattic/editor before.

The special `compositionstart` and `compositionend` events are emitted before and after the user starts to input text using a special foreign input method. Input Method Editors can perform manipulations of text content on their own, and they expect the caret to stay still. Moving the caret can easily break things.

A simple way of handling this is to take notice of the events, store a flag marking that a composition is taking place and don't do anything with the input while a composition is taking place. That's what we do [here](https://github.com/Automattic/editor/blob/master/lib/editor-normalizer/index.ts#L105-L106), in the `editor-normalizer` module.

**Comment by vhikd** [comment]
Any suggestions? I can't find any way to solve this problem.

**Comment by bummytime** [comment]
> Any suggestions? I can't find any way to solve this problem.

@vhikd are you asking about how to solve this from a development perspective or as an app user?

**Comment by vhikd** [comment]
@bummytime ,I am a developer.I want to find a way to solve this problem. I have been working on it more than a day. And I can't find any way to change it better. Could you help me to solve this problem?

**Comment by bummytime** [comment]
@vhikd Gotcha. 

Well, I would probably start with the suggestion @coreh made above - capture the ```compositionstart``` and ```compositionend``` events [here](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/85f5d7b3fe755032b24a588cfd37be09ad706860/Assets/ZSSRichTextEditor.js#L1666) and set a new flag which would restrict any additional input in the ```ZSSField``` when this flag is true. In terms of where to restrict input, [this](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/85f5d7b3fe755032b24a588cfd37be09ad706860/Assets/ZSSRichTextEditor.js#L1741) would be a good place to start looking.

Good luck!

**Comment by vhikd** [comment]
@bummytime , I'm not familiar with js . I had try anyway in iOS develop, and I can't find a way to get it done. I will try to add a flag in the js file to handle different events.
Thanks for your reply.
