### ISSUE TITLE
Title jank when toggle html/visual views

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#592]
Let's get rid of the title animation/jank when toggling between visual & html

video: https://lookback.io/watch/9tDN4rnvLfn4GD4Aq

**Comment by thianhlu** [comment]
Specifically, the Post title is shifting down 1px and the linebreak/hr is shifting up 1px and darkening.

**Comment by bummytime** [comment]
The linebreak we can address. However the shift that occurs when switching modes may be a little tougher because we are actually swapping from a `UIWebView` to a native `UITextView`. This feature: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/335 would probably help matters.

**Comment by thianhlu** [comment]
Dumb question but can't we place them in the exact same location x, y wise so the post title stays in same spot? Or are we adding in some padding on the uiview that we cant really add in the uitextview

**Comment by bummytime** [comment]
@thinah We can play around with positioning and see if we can get things to line up better.

**Comment by bummytime** [comment]
Ok @thianhlu & @meremagee I have a PR coming down the pipe that should help matters here. Note that part of the "jumping" y'all are seeing is due to the QuickType bar appearing in visual mode and not in HTML:

![scaled_screen_shot_2015-04-03_at_2_22_33_pm](https://cloud.githubusercontent.com/assets/154014/6987545/d4727b06-da0d-11e4-8e29-ddbde703588f.png)

![scaled_screen_shot_2015-04-03_at_2_24_45_pm](https://cloud.githubusercontent.com/assets/154014/6987546/d703bc72-da0d-11e4-9db3-c8d26eeaf041.png)

**Comment by bummytime** [comment]
One more thing to note: in HTML mode the title is fixed whereas in Visual mode it is not. This will account for some of the scrolling differences between modes.

Ref: #335

**Comment by meremagee** [comment]
Looks much better. Thanks for the clarification around the difference in fixed/scrolled @bummytime
