### ISSUE TITLE
inputView for webview

### ISSUE THREAD

**Issue by tinhbka** [wordpress-mobile/WordPress-Editor-iOS#686]
How to set inputView for webview, i want to custom keyboard. please help!

**Comment by bummytime** [comment]
Not sure what you are really asking for here @tinhbka.

**Comment by bummytime** [comment]
@tinhbka If you are asking how to implement a custom input view on a `UIWebVIew`, we are not doing that in this project. We *are* using a custom input accessory view. See:

https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/75fb2a143151ce6c9e255e5ee98527fe330a04ca/Classes/UIWebView%2BGUIFixes.m

Since your question is more general, I would consider asking it on Stack Overflow or somewhere else similar.

**Comment by tinhbka** [comment]
ok tks for care
