### ISSUE TITLE
Provide an easier way to create drafts

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#712]
A user requested an easier way to create a draft with the app. At the moment you have to click through to Settings and change the status to Draft. On the desktop version all you have to do is click “Save Draft”. It would be nice to have similar functionality in the app.

/cc @thianhlu

**Comment by thianhlu** [comment]
:+1:

**Comment by diegoreymendez** [comment]
There is already an easy way to save as draft, which is to:

1. Create a post
2. Tap X
3. Save as Draft.

However, while useful... it may be non-obvious.

My suggestion would be to replace the publish button with a "Done" or "Save" button for a post that was never published and, the first time the user taps on it, ask if they want to save the post as a draft, or just post it right away.

**Comment by lizkarkoski** [comment]
I have a user in the public support forums requesting an easier way to save a draft, particularly, an auto save feature. http://en.forums.wordpress.com/topic/wp-app-for-iphone-abandoning-my-blog-drafts

**Comment by diegoreymendez** [comment]
Thanks for the report @lizkarkoski.

Pinging @rachelmcr to make sure this is triaged.

**Comment by rachelmcr** [comment]
I'd say we're resolving this issue in 6.8 (available in the app store soon) with the addition of a "Save as draft" quick action on new drafts: https://github.com/wordpress-mobile/WordPress-iOS/pull/6207

Users will be able to tap the ellipsis menu in the top right and select "Save as draft." (This addresses the original issue of making it easier to save drafts to the server; I think an auto save feature would need to be discussed separately.)

Marking this issue as resolved since this will be released with version 6.8.
