### ISSUE TITLE
Pasting a Mesh URL fails silently

### ISSUE THREAD

**Issue by jasmussen** [wordpress-mobile/WordPress-Editor-iOS#713]
Steps to reproduce:

- On an iPhone, copy a YouTube URL, go to the WordPress editor and start a new post
- Paste the URL and notice how it works. On publish the YouTube video is properly oembedded.
- Now copy a Mesh URL, for example https://me.sh/109caiz1, then go to the WordPress editor and start a new post
- Paste the Mesh URL in the editor, and notice how nothing happens. If you paste between two text paragraphs, in fact the empty paragraph gets removed when pasting.

The result is you can't embed meshes from WordPress iOS.

Here's a video of the behavior:

https://cloudup.com/chaBXqG0C5Y

**Comment by kwonye** [comment]
@frosty I believe this is the same underlying cause as the safari share issue.

**Comment by frosty** [comment]
Yep, so it looks as though this is due to differing `clipboardData` data types. When getting clipboard data in JavaScript, you must specify the type of data you want to retrieve – for example:

```
var plainText = clipboardData.getData('text/plain');
```

Links copied via YouTube are available as both plain text and with the `text/uri-list` data type. However, links copied via Safari are only available as the latter. We were previously only fetching data from the clipboard as plain text, which is why these Safari links were getting ignored. Fix coming up...
