### ISSUE TITLE
replaceLocalImageWithRemoteImage doesn't work

### ISSUE THREAD

**Issue by michaelmou** [wordpress-mobile/WordPress-Editor-iOS#792]
thanks your code , and i have some questions, which moment can I use the method "replaceLocalImageWithRemoteImage"?? I used it after it was a local image, and i have no mediaId, after invoked the method, nothing was happen.what's wrong?? how can i get the mediaId, does it important to this method??

**Comment by michaelmou** [comment]
And I try removeImage else, it doesn't work neither.

**Comment by SergioEstevao** [comment]
The purpose of that method is to insert a local image while an upload is happening to the server, and when the upload is finished and you have the final url of the image to replace the local url for the remote url.
The media ID is important because is how the code finds the local image to replace it. You can generate any random ID and associate it with that particular image.

If you just want to insert an image that already is on a server you can use the "insertImage" method.

**Comment by GioValentin** [comment]
what is the point of having a uniqueID and a mediaID. are they the same thing?
