### ISSUE TITLE
When creating a new post,the bold can not be used.

### ISSUE THREAD

**Issue by wakingwwk** [wordpress-mobile/WordPress-Editor-iOS#863]
Steps to reproduce:
1.Creating a new post (or deleting all the text out of an exiting one)
2.Click the 'B'（Enable bold）
3.Select the content field.
4.Input text

But no bold text

**Comment by rachelmcr** [comment]
Thanks for the report! There is an issue with formatting text at the very beginning of a post, which we're tracking here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/754

It sounds like that's the bug here, so I'm going to close this duplicate report. Please let us know if you're seeing a larger issue with formatting.
