### ISSUE TITLE
Previewing a post counts as view activity for stats

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#99]
Original Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/2049

Per @kevmarsden:
>When using the iOS app, a site’s page views stats are increased when a post is previewed. This affects sites when the visibility set to either Public or Private.
>
>This issue was reported by a user in [Helpshift] (https://automattic.helpshift.com/admin/issue/927/) and I was able to replicate it on my test sites. I was not able to replicate this issue using WordPress.com in a web browser.

**Comment by rachelmcr** [comment]
I tested this in WPiOS 6.2.0.20160429 (using iPhone 6, iOS 9.3.1). I can no longer reproduce this issue. I always get a logged-in view of the posts, and my view is only counted in stats when viewing a published post on a private blog (expected behavior). In other cases, the view stats don't change for the posts I viewed.
